Peopleware Chapter 8: "You Never Get Anything Done around Here between 9 and 5."

diff --git a/.github/workflows/index.yaml b/.github/workflows/index.yaml
--- a/.github/workflows/index.yaml
+++ b/.github/workflows/index.yaml
@@ -1,17 +1,26 @@
-  name: Smoke Tests
-  on: push
-  jobs:
-    build:
+ name: Smoke Tests
+ on: push
+ jobs:
+   build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Generate random exit status 0 or 1
+        run: |
+          exit_status=$(( ( RANDOM % 2)  + 1 -1 ))
+          echo "Exit status $exit_status"
+          exit $exit_status
+   deploy:
       runs-on: ubuntu-latest
+      needs: 
+        - build
+      if: ${{ always() }}    
       steps:
-        - run: exit 0
-    deploy:
-       runs-on: ubuntu-latest
-       needs: 
-         - build  
-       if: ${{ failure() }}
-       steps:
-         - name: Run if ANY of the previous step of a this job fails!
-           run: |
-             echo "Dependent job failed!"
-             exit 1
+        - name: Fail the job if result is not success
+          if: ${{ needs.build.result != 'success'}}
+          run: |
+            echo "Dependent job failed!"
+            exit 1
+        - name: Run job if result is success
+          run: |
+            echo "Dependent job succeeded!"
+             exit 0
