Update index.yaml

diff --git a/.github/workflows/index.yaml b/.github/workflows/index.yaml
--- a/.github/workflows/index.yaml
+++ b/.github/workflows/index.yaml
@@ -5,18 +5,21 @@ jobs:
   ci:
     runs-on: ubuntu-latest
     steps:
-      - run: exit 1
+      - run: |
+
+          exit $(( ( RANDOM % 2)  + 1 - 1 ))
   build:
      runs-on: ubuntu-latest
-     needs: ci
-     if: always()
-     env:
-       conclusion: $     
+     needs: 
+       - ci
+     if: always()    
      steps:
-       - run: |
-          echo "Result = $conclusion"
-          if [ ${conclusion} == "success" ]; then
-              exit 0
-          else
-              exit 1
-          fi
+       - name: Fail the job if result is not success
+         if: ${{ needs.build.result != 'success'}}
+         run: | 
+           echo "Dependent job failed!"
+           exit 1
+       - name: Run job if result is success
+         run: |
+           echo "Dependent job succeeded!"
+            exit 0
