Reticulating splines...

diff --git a/.github/workflows/index.yaml b/.github/workflows/index.yaml
--- a/.github/workflows/index.yaml
+++ b/.github/workflows/index.yaml
@@ -1,19 +1,18 @@
 name: Smoke Tests
 on: push
 jobs:
-  build_and_deploy:
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - run: exit 1
+  deploy:
      runs-on: ubuntu-latest
+     needs: 
+       - build
+     if: ${{ always() }}    
      steps:
-       - name: Build
-         run: |
-           echo "Running build"
-           exit 0
-       - name: Deploy
-         run: |
-           echo "Running deploy"
-           exit 1  
        - name: One of the previous steps of this job failed
          if: ${{ failure() }}
          run: |
-           echo "Fails if any of the previous step of a this fails!"
+           echo "Run if any of the previous step of a this job fails!"
            exit 1
